### ISSUE TITLE
Client not connecting.

### ISSUE THREAD

**Issue by Hotallday** [iiegor/xat-www#2]
I don't know if is just me but,
If I login to my account the client stops sending packets to the server.
The only way it sends packets again is if I clear the chat local storage.

**Comment by iiegor** [comment]
@Hotallday strange :confused: Are you sure that you have properly configured your hosts file?
You need to have something like this: ``127.0.0.1 xat.dev www.xat.dev``

**Comment by Hotallday** [comment]
@iiegor Yes, it all works except the client stops sending packets after I login.

**Comment by iiegor** [comment]
@Hotallday Hello again, is this still happening?

**Comment by Hotallday** [comment]
@iiegor No. It was because of me using the wrong database.
